export const MenuData = [
    [
        {
            key:'sub1',
            icon:'user',
            name:'subNav1',
            subMenu:[
                {
                    id:'1',
                    name:'options1',
                    linkTo:'/'
                },{
                    id:'2',
                    name:'options2',
                    linkTo:'/table'
                },{
                    id:'3',
                    name:'options3',
                    linkTo:'/doc'
                },{
                    id:'4',
                    name:'options4',
                    linkTo:'/home'
                }
            ]
        },
        {
            key:'sub2',
            icon:'laptop',
            name:'subNav2',
            subMenu:[
                {
                    id:'5',
                    name:'options5',
                    linkTo:'/404'
                }
            ]
        },
        {
            key:'sub3',
            icon:'notification',
            name:'subNav3',
            subMenu:[
                {
                    id:'6',
                    name:'options6',
                    linkTo:'/404'
                }
            ]
        }
    ],[
        {
            key:'sub11',
            icon:'code',
            name:'菜单一',
            subMenu:[
                {
                    id:'1',
                    name:'options1',
                    linkTo:'/404'
                },{
                    id:'2',
                    name:'options2',
                    linkTo:'/404'
                },{
                    id:'3',
                    name:'options3',
                    linkTo:'/404'
                },{
                    id:'4',
                    name:'options4',
                    linkTo:'/404'
                }
            ]
        },
        {
            key:'sub22',
            icon:'delete',
            name:'菜单二',
            subMenu:[
                {
                    id:'5',
                    name:'options5',
                    linkTo:'/404'
                }
            ]
        },
        {
            key:'sub33',
            icon:'stock',
            name:'菜单三',
            subMenu:[
                {
                    id:'6',
                    name:'options6',
                    linkTo:'/404'
                }
            ]
        }
    ],[
        {
            key:'sub111',
            icon:'eye',
            name:'新菜单一',
            subMenu:[
                {
                    id:'1',
                    name:'options1',
                    linkTo:'/404'
                },{
                    id:'2',
                    name:'options2',
                    linkTo:'/404'
                },{
                    id:'3',
                    name:'options3',
                    linkTo:'/404'
                },{
                    id:'4',
                    name:'options4',
                    linkTo:'/404'
                }
            ]
        },
        {
            key:'sub222',
            icon:'message',
            name:'新菜单二',
            subMenu:[
                {
                    id:'5',
                    name:'options5',
                    linkTo:'/404'
                }
            ]
        },
        {
            key:'sub333',
            icon:'qrcode',
            name:'新菜单三',
            subMenu:[
                {
                    id:'6',
                    name:'options6',
                    linkTo:'/404'
                }
            ]
        }
    ]
];